from django.db import models


class Questions(models.Model):
    Set = models.IntegerField()
    Number = models.IntegerField()
    Content = models.CharField(max_length=255)
    Option_1 = models.CharField(max_length=255)
    Option_2 = models.CharField(max_length=255)
    Option_3 = models.CharField(max_length=255)
    Option_4 = models.CharField(max_length=255)
    Multi_Choice = models.BooleanField()
    Option_1_Correct = models.BooleanField()
    Option_2_Correct = models.BooleanField()
    Option_3_Correct = models.BooleanField()
    Option_4_Correct = models.BooleanField()


class UserQuestions(models.Model):
    User_ID = models.CharField(max_length=30)
    Set_Id = models.IntegerField()
    Attempt = models.IntegerField()
    Question_1 = models.IntegerField()
    Question_2 = models.IntegerField()
    Question_3 = models.IntegerField()
    Question_4 = models.IntegerField()
    Question_5 = models.IntegerField()
    Question_6 = models.IntegerField()
    Question_7 = models.IntegerField()
    Question_8 = models.IntegerField()
    Question_9 = models.IntegerField()
    Question_10 = models.IntegerField()
    Question_10 = models.IntegerField()
    Question_1_Status = models.IntegerField()
    Question_2_Status = models.IntegerField()
    Question_3_Status = models.IntegerField()
    Question_4_Status = models.IntegerField()
    Question_5_Status = models.IntegerField()
    Question_6_Status = models.IntegerField()
    Question_7_Status = models.IntegerField()
    Question_8_Status = models.IntegerField()
    Question_9_Status = models.IntegerField()
    Question_10_Status = models.IntegerField()
    Correct_Option = models.CharField(max_length=10)
