# Generated by Django 3.1.7 on 2021-02-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Set', models.IntegerField()),
                ('Number', models.IntegerField()),
                ('Content', models.CharField(max_length=255)),
                ('Option_1', models.CharField(max_length=255)),
                ('Option_2', models.CharField(max_length=255)),
                ('Option_3', models.CharField(max_length=255)),
                ('Option_4', models.CharField(max_length=255)),
                ('Correct_Answer', models.CharField(max_length=10)),
            ],
        ),
    ]
