# Generated by Django 3.1.7 on 2021-02-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='Correct_Answer',
            new_name='Correct_Option',
        ),
    ]
