# Generated by Django 3.1.7 on 2021-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210225_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField()),
                ('SetName', models.IntegerField()),
                ('Attempt', models.IntegerField()),
                ('Question_1', models.IntegerField()),
                ('Question_2', models.IntegerField()),
                ('Question_3', models.IntegerField()),
                ('Question_4', models.IntegerField()),
                ('Question_5', models.IntegerField()),
                ('Question_6', models.IntegerField()),
                ('Question_7', models.IntegerField()),
                ('Question_8', models.IntegerField()),
                ('Question_9', models.IntegerField()),
                ('Question_10', models.IntegerField()),
                ('Question_1_Status', models.IntegerField()),
                ('Question_2_Status', models.IntegerField()),
                ('Question_3_Status', models.IntegerField()),
                ('Question_4_Status', models.IntegerField()),
                ('Question_5_Status', models.IntegerField()),
                ('Question_6_Status', models.IntegerField()),
                ('Question_7_Status', models.IntegerField()),
                ('Question_8_Status', models.IntegerField()),
                ('Question_9_Status', models.IntegerField()),
                ('Question_10_Status', models.IntegerField()),
                ('Option_2', models.CharField(max_length=255)),
                ('Option_3', models.CharField(max_length=255)),
                ('Option_4', models.CharField(max_length=255)),
                ('Correct_Option', models.CharField(max_length=10)),
            ],
        ),
    ]
