# Generated by Django 3.1.7 on 2021-02-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_userquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestions',
            old_name='SetName',
            new_name='SetId',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='Option_2',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='Option_3',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='Option_4',
        ),
    ]
