# Generated by Django 3.1.7 on 2021-02-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210226_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestions',
            old_name='SetId',
            new_name='Set_Id',
        ),
    ]
