# Generated by Django 3.1.7 on 2021-02-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210226_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Multi_Choice',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
