# Generated by Django 3.1.7 on 2021-02-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_questions_multi_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Answered',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
