# Generated by Django 3.1.7 on 2021-02-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_questions_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='Answered',
        ),
    ]
