# Generated by Django 3.1.7 on 2021-02-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_questions_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='Correct_Option',
        ),
        migrations.AddField(
            model_name='questions',
            name='Option_1_Correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Option_2_Correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Option_3_Correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='Option_4_Correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
