# Generated by Django 3.1.7 on 2021-03-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20210227_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestions',
            name='User_ID',
            field=models.CharField(max_length=30),
        ),
    ]
